// Auto-generated from translations/ui_strings.csv
// Do not edit directly - run: npx tsx scripts/build-translations.ts

export type TranslationKey =
  | "\"Add a scenario called 'Improved Access'\""
  | "\"Compare safety outcomes across all scenarios\""
  | "\"What are the key differences between the base case and scenario 1?\""
  | "\"Show me the data sources used for this analysis\""
  | "\"What happens if we increase facility access to 80%?\""
  | "\"Create a summary report for policymakers\""
  | "\"Show me the flow diagram from baseline to outcomes\""
  | "\"How many safe abortions would result from improving family planning?\""
  | "\"Based on the uploaded documents, what data sources are available for this country?\""
  | "\"Review the uploaded National Strategy for Abortion Care and interpret our analysis findings with reference to the national targets\""
  | "About"
  | "Add scenarios"
  | "Add or delete scenarios"
  | "AI"
  | "AI Analysis Assistant"
  | "Analyze and compare scenario results"
  | "Are you sure you want to delete this project?"
  | "Are you sure you want to delete this scenario?"
  | "Base case"
  | "Baseline data source"
  | "Cancel"
  | "Capturing charts..."
  | "Charts"
  | "Clear all data"
  | "Click \"Add scenarios\" to create one"
  | "Country"
  | "Country:"
  | "Country name"
  | "Create"
  | "Create new project"
  | "Create new report"
  | "Create new scenarios"
  | "Create your first project"
  | "CSV upload"
  | "Current report:"
  | "Custom"
  | "Data manifest not yet loaded"
  | "Default scenarios"
  | "Definitions"
  | "Delete project"
  | "Documents"
  | "Delete scenario"
  | "Drag and drop to reorder scenarios"
  | "Duplicate"
  | "Duplicate project"
  | "Duplicating project"
  | "Edit and reorder"
  | "Edit and reorder scenarios"
  | "Edit project"
  | "Edit report"
  | "Edit scenario"
  | "Enter country name..."
  | "Error"
  | "Example prompts"
  | "Failed to generate report"
  | "Failed to update report"
  | "File:"
  | "File size must be less than 500MB"
  | "Generate report"
  | "Generating..."
  | "Generating report with AI..."
  | "Got it"
  | "Health system building blocks:"
  | "Health system scenarios"
  | "Import confirmation"
  | "Importing this CSV file will replace all current parameters in this project with the data from the CSV file including the base case and all scenarios. This action cannot be undone."
  | "Imported:"
  | "Improvement due to scenario"
  | "No change"
  | "Not specified"
  | "Base case proportion of abortions that are safe"
  | "Base case proportion of women with abortion complications who receive effective care"
  | "Initial data source"
  | "Inputs"
  | "Last modified"
  | "Loading..."
  | "Loading data sources..."
  | "Modify scenario parameters"
  | "New name must be different from current name"
  | "New project"
  | "New project name"
  | "No project ID provided"
  | "No projects found. Create one to get started."
  | "No documents uploaded"
  | "No scenarios"
  | "No scenarios yet"
  | "Number of unintended pregnancies"
  | "Only PDF files are supported"
  | "Original data:"
  | "Original file:"
  | "Pathway"
  | "Please enter a prompt"
  | "Please enter what you'd like to change"
  | "Pregnancies"
  | "Pregnancy outcomes"
  | "Project name"
  | "Project not found:"
  | "Projects"
  | "Proportion of abortions that are safe"
  | "Proportion of pregnancies resulting in miscarriage"
  | "Proportion of women with abortion complications who receive effective care"
  | "R script"
  | "Rendering charts to images..."
  | "Reports"
  | "Reset all"
  | "Reset base case to original"
  | "Results"
  | "Return to Home"
  | "Save"
  | "Saving report..."
  | "Scenario"
  | "scenario"
  | "scenarios"
  | "Scenario name"
  | "Scenarios"
  | "Select adjustments"
  | "Select one or more templates to create scenarios"
  | "Select scenarios to include (the base case is always included)"
  | "Selected data source not found"
  | "Show R script tab in Results pane"
  | "Show system context tab in AI pane"
  | "Source:"
  | "System context"
  | "Table"
  | "Type your message... (Shift+Enter for new line)"
  | "The proportion of all pregnancies that naturally end in miscarriage before seeking abortion care."
  | "The total number of unintended pregnancies in the population during the time period being modeled."
  | "Thinking..."
  | "This will permanently delete all projects. This action cannot be undone."
  | "This will reset all base case parameters to their original imported values (details below). This action cannot be undone."
  | "Update report"
  | "Upload PDF"
  | "Upload PDFs to include in AI analysis"
  | "Upload PDF documents in the Documents tab to include them in AI analysis. The assistant can read and reference these documents when answering questions or generating reports. Documents are included automatically in the first message of each conversation."
  | "Use this assistant to analyze your scenario results and modify parameters and manage scenarios."
  | "User context"
  | "Updating..."
  | "Updating report with AI..."
  | "View specific results and metrics"
  | "What would you like the report to focus on?"
  | "What would you like to change?"
  | "What you can do"
  | "You can create and edit reports either with this assistant or using the \"Create report\" button on the Reports pane itself."
  | "You must enter a country name"
  | "You must enter a project name"
  | "You must select a data source"
  | "Abortion seeking"
  | "Facility access"
  | "Out-of-facility access"
  | "Facility readiness"
  | "Out-of-facility readiness"
  | "Family planning"
  | "Health worker competent in abortion care"
  | "Misoprostol"
  | "Mifepristone"
  | "Vacuum aspiration kit (MVA, EVA kit)"
  | "Dilation and evacuation kit (D&E kit)"
  | "Dilation and curettage kit (D&C kit)"
  | "Disposable latex gloves (sterile)"
  | "Antiseptic for cleaning cervix"
  | "Antibiotics"
  | "CEmONC"
  | "Other items for non-recommended out-of-facility services"
  | "Custom scenario"
  | "Set multiple parameters to your own specified values"
  | "Improve facility access"
  | "Increase all facility access parameters to at least 90% (except legal restrictions)"
  | "Improve facility readiness"
  | "Increase all facility readiness parameters to at least 90% (except D&C)"
  | "Increase preference for facility-based care"
  | "Increase the proportion of women preferring facility-based care (vs out-of-facility care) to at least 90%"
  | "Workforce"
  | "Increase facility health worker abortion competency to at least 90%"
  | "Commodities"
  | "Increase all facility commodity readiness parameters to at least 90% (except health workers, D&C kits, and CEmONC)"
  | "Governance"
  | "Remove legal restrictions for 100% of abortions"
  | "Financing"
  | "Reduce financial barriers such that at least 90% of women can afford facility and out-of-facility care"
  | "Facility: "
  | "Out-of-facility: "
  | "Proportion of unintended pregnancies for which abortion is sought"
  | "Proportion of women seeking an induced abortion whose preference is to initiate abortion in a facility"
  | "Proportion of unintended pregnancies for which abortion is not legally restricted"
  | "Proportion of facilities offering abortion services"
  | "Proportion of facilities offering post-abortion care services"
  | "Proportion of women within accessible distance of a facility"
  | "Proportion of women for whom the cost of facility-based care is not a barrier"
  | "Proportion of women within accessible distance of an out-of-facility provider"
  | "Proportion of women for whom the cost of out-of-facility care is not a barrier"
  | "Demand for family planning"
  | "Met need for family planning"
  | "Combined effectiveness of contraceptive methods"
  | "This indicator refers to the proportion of women experiencing an unintended pregnancy who choose to seek an abortion. An abortion (or termination) is the medical process of ending a pregnancy. Abortion is a common health intervention. It is very safe when carried out using a method recommended by WHO, appropriate to the pregnancy duration and by someone with the necessary skills."
  | "This indicator refers to the proportion of women who choose to seek an abortion, who have a preference to engage with facility-based abortion care services based on knowledge, awareness, trust, and interest in facility based care."
  | "This indicator refers to the proportion of women who choose to seek an abortion, who will be able to access facility based care in accordance with the legal context of abortion in their country. Restrictive laws and requirements that are not medically justified include criminalization of abortion, mandatory waiting periods, provision of biased information or counselling, third-party authorization and restrictions regarding the type of health care providers or facilities that can provide abortion services."
  | "This indicator refers to the proportion of healthcare facilities who offer abortion care services of any kind (including comprehensive abortion care, and post abortion care)."
  | "This indicator refers to the proportion of healthcare facilities who offer post-abortion care services."
  | "This indicator refers to the proportion of women who choose to seek an abortion, who will be able to access a healthcare facility based on their geographic distance from a healthcare facility."
  | "This indicator refers to the proportion of women who choose to seek facility-based abortion care, for whom associated costs will not be a barrier (including loss of income, payment for abortion care services, and other financial costs)."
  | "This indicator refers to the proportion of women who choose to seek an abortion, who will be able to access an out-of-facility provider (including pharmacy, telehealth, or traditional provider) based on their geographic distance from an out-of-facility provider."
  | "This indicator refers to the proportion of women who choose to seek out-of-facility-based abortion care, for whom associated costs will not be a barrier (including loss of income, payment for abortion care services, and other financial costs)."
  | "This indicator refers to the proportion of women who don't want pregnancy, who want access to family planning services and contraception."
  | "This indicator refers to the proportion of women who want access to family planning services and contraception and have this demand met."
  | "This indicator refers to combined effectiveness of family planning services and contraceptive methods."
  | "This indicator refers to the proportion of facilities offering abortion services, whose health workforce are appropriately knowledgeable and trained to provide abortion care services in accordance with the WHO Family planning and comprehensive abortion care toolkit for the primary health care workforce guidelines."
  | "This indicator refers to the proportion of facilities offering abortion services, who have misoprostol available as a commodity for facility-based abortion care."
  | "This indicator refers to the proportion of facilities offering abortion services, who have mifepristone available as a commodity for facility-based abortion care."
  | "This indicator refers to the proportion of facilities offering abortion services, who have a vacuum aspiration kit (MVA, EVA) available as a commodity for facility-based abortion care."
  | "This indicator refers to the proportion of facilities offering abortion services, who have a dilation and evacuation kit (D&E) available as a commodity for facility-based abortion care."
  | "This indicator refers to the proportion of facilities offering abortion services, who have a dilation and curettage kit (D&C) available as a commodity for facility-based abortion care."
  | "This indicator refers to the proportion of facilities offering abortion services, who have disposable latex gloves available as a commodity for facility-based abortion care."
  | "This indicator refers to the proportion of facilities offering abortion services, who have antiseptic available as a commodity for facility-based abortion care."
  | "This indicator refers to the proportion of facilities offering abortion services, who have antibiotics available as a commodity for facility-based abortion care."
  | "This indicator refers to the proportion of facilities offering CEmONC for facility-based post-abortion care."
  | "This indicator refers to the proportion of out-of-facility service providers who are appropriately knowledgeable and trained to correctly dispense a WHO-recommended medical abortion regimen (mifepristone + misoprostol or correct misoprostol-only dosing), and provide the minimum essential counselling (how to take the drugs, expected bleeding/pain, when to seek care for warning signs)."
  | "This indicator refers to the proportion of out-of-facility service points who have misoprostol available as a commodity to provide abortion care."
  | "This indicator refers to the proportion of out-of-facility service points who have mifepristone available as a commodity to provide abortion care."
  | "This indicator refers to the proportion of out-of-facility service points who have other non-recommended products available to provide abortion care."
  | "Misoprostol and mifepristone"
  | "Misoprostol only"
  | "Vacuum aspiration"
  | "Dilation and evacuation"
  | "Dilation and curettage"
  | "Misoprostol and mifepristone, without a competent health worker"
  | "Misoprostol only, without a competent health worker"
  | "Vacuum aspiration, without a competent health worker"
  | "Dilation and evacuation, without a competent health worker"
  | "Dilation and curettage, without a competent health worker"
  | "All other out-of-facility services"
  | "New scenario"
  | "Welcome"
  | "Using the Tool"
  | "Model Methodology"
  | "FAQ"
  | "Go to projects"
  | "No reports yet"
  | "Select a report..."
  | "Word"
  | "Create report"
  | "No report selected"
  | "Create a new report or select one from the dropdown"
  | "AI-Generated Content"
  | "This report was generated using artificial intelligence. Please review all content for accuracy and verify any critical information."
  | "Created:"
  | "Updated:"
  | "System prompt"
  | "Results text"
  | "Copy"
  | "Edit"
  | "Add custom context to include in all AI interactions"
  | "No user context provided"
  | "Enter additional context for the AI assistant..."
  | "Unknown"
  | "Survey"
  | "Administrative"
  | "Estimate"
  | "Assumption"
  | "Literature"
  | "Expert opinion"
  | "Unclassified"
  | "Strong evidence"
  | "Moderate evidence"
  | "Weak evidence"
  | "Non-recommended"
  | "Data source description"
  | "Data Sources"
  | "Parameter category"
  | "Data source"
  | "Source type"
  | "Evidence strength"
  | "Data source:"
  | "Source type:"
  | "Evidence strength:"
  | "Definition:"
  | "Are you sure you want to delete this report?"
  | "Standard"
  | "Summary"
  | "Full detail"
  | "Unintended pregnancies"
  | "Seek an induced abortion"
  | "Do not seek an abortion"
  | "Abortion initiated in a facility"
  | "Abortion initiated out of a facility"
  | "No access"
  | "Safe"
  | "Less safe"
  | "Least safe"
  | "No abortion"
  | "Safe abortion"
  | "Safe, less safe, and least safe abortions"
  | "Less safe abortion"
  | "Least safe abortion"
  | "Abortion complication"
  | "Return to a state of non-pregnancy"
  | "Effective post-abortion care"
  | "No care or ineffective care"
  | "All pregnancies"
  | "Intended pregnancies"
  | "Miscarriage"
  | "Live birth"
  | "Moderate complication"
  | "Severe complication"
  | "No access or abortion"
  | "Prefer facility-based care"
  | "Prefer out-of-facility care"
  | "Legal access"
  | "No legal access"
  | "Geographic access"
  | "No geographic access"
  | "Financial access"
  | "No financial access"
  | "Service availability"
  | "No service availability"
  | "Clear"
  | "AI Analysis Assistant"
  | "Ask me to analyze your scenario results or create reports or add new scenarios."
  | "Facility services"
  | "Out-of-facility services"
  | "Complication rates"
  | "Service"
  | "Combo"
  | "Moderate"
  | "Severe"
  | "Incomplete abortion"
  | "Continuing pregnancy"
  | "Infection"
  | "Trauma"
  | "Hemorrhage"
  | "Other"
  | "All other out-of-facility services"
  | "SAFE"
  | "LESS SAFE"
  | "LEAST SAFE"
  | "MODERATE"
  | "SEVERE"
  | "STRONG EVIDENCE"
  | "MODERATE EVIDENCE"
  | "WEAK EVIDENCE"
  | "About"
  | "Indicator"
  | "Pregnancies"
  | "All pregnancies"
  | "Intended pregnancies"
  | "Demand"
  | "Access"
  | "Service provision at facilities"
  | "Service provision at out-of-facility providers"
  | "Abortion outcomes"
  | "Abortions"
  | "Live births"
  | "Miscarriages"
  | "Total abortions"
  | "Abortion complications"
  | "Total abortion complications"
  | "Complication categories"
  | "Total moderate complications"
  | "Total severe complications"
  | "No complications"
  | "Post-abortion care for abortion complications"
  | "Pregnant women seeking an induced abortion"
  | "Rerouted from facility to out-of-facility"
  | "No abortion after initiating in a facility"
  | "No abortion after initiating out of a facility"
  | "Unknown error"
  | "Non-recommended"
  | "Change from the base case"
  | "Proportion of pregnancies resulting in contraindication"
  | "The proportion of all pregnancies that have medical contraindications requiring therapeutic abortion."
  | "Abortion service provision at facilities"
  | "Abortion service provision at out-of-facility providers"
  | "Receiving effective care"
  | "Not receiving effective care"
  | "Total moderate complications needing care"
  | "Total severe complications needing care"
  | "Total complications needing care"
  | "Seek an induced abortion"
  | "Complications"
  | "Total complications"
  | "Moderate complications (total)"
  | "Severe complications (total)"
  | "Reset to original value"
  | "CSV file is empty"
  | "CSV must have a 'BASE' column"
  | "Invalid number value"
  | "Invalid percentage value"
  | "You have not yet created any scenarios, so this report will concern the base case only."
  | "e.g., Compare family planning outcomes across all scenarios"
  | "e.g., Summarize the baseline abortion care pathways and outcomes"
  | "e.g., Add a section comparing safety outcomes, or change the tone to be more technical";
